name: UltimateDonors
version: 0.0.7
main: me.Stefan923.UltimateDonors.UltimateDonors
description: Provides an useful set of commands and donors utilities.
softdepend: [SuperCore]
authors: [Stefan923]

commands:
  ultimatedonors:
    description: Infos about this plugin.
    aliases: [donors, udonors]
  emotes:
    description: Shows a list with the emotes you can use.
    aliases: [ultimatedonorsemotes, donorsemotes, udemotes, emojis, emote, emoji]

permissions:
  ultimatedonors.admin:
    description: Access to powerfull commands, like /donors reload.
    default: op
  ultimatedonors.use.emotes:
    description: Access to use emotes.
    default: op